// Code generated by "stringer -type=registryName -output=storeregistry_string.go"; DO NOT EDIT.

package dbcommon

import "strconv"

const (
	_registryName_name_0 = "MessagedbDatabaseMessagedbShardDatabaseMessagedbEncryDatabaseMessagedbOldDatabaseMessagedbPtsHandleDatabaseChanneldbDatabaseChanneldbMsgShardDatabaseChanneldbEncryDatabaseChanneldbOldDatabaseChanneldbPtsHandleDatabasePotatoDcConfigDatabasePotatoAccountDatabasePotatoUserDatabasePotatoChannelDatabasePotatoGroupDatabasePotatoMonitorDatabasePotatoCommonDatabasePotatoAppliedDatabasePotatoSecurityChatDatabasePotatoPrivateChatHistoryDatabasePotatoSecurityChatDiffMessageDatabasePotatoConfigDatabasePotatoProxyConfigDatabasePotatoUserGpsDatabasePotatoUserBotPotatoUserSessionDatabaseMessageRedisMessageShardRedisMessageRedisScriUserInfoRedisAuthorizationRedisBasicGroupRedisMediaPushRedisMediaPullRedisMesageIncreaseRedis"
	_registryName_name_1 = "ChannelMessageRedisChannelMessageShardRedisPtNatsPtRouteNatsPtMemNatsPtMomentNatsPtCircleFriendPtRedisESUnknown"
)

var (
	_registryName_index_0 = [...]uint16{0, 17, 39, 61, 81, 107, 124, 149, 171, 191, 217, 239, 260, 278, 299, 318, 339, 359, 380, 406, 438, 475, 495, 520, 541, 554, 579, 591, 608, 624, 637, 655, 670, 684, 698, 717}
	_registryName_index_1 = [...]uint8{0, 19, 43, 49, 60, 69, 81, 95, 104, 111}
)

func (i registryName) String() string {
	switch {
	case 4001 <= i && i <= 4035:
		i -= 4001
		return _registryName_name_0[_registryName_index_0[i]:_registryName_index_0[i+1]]
	case 4037 <= i && i <= 4045:
		i -= 4037
		return _registryName_name_1[_registryName_index_1[i]:_registryName_index_1[i+1]]
	default:
		return "registryName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
