// Code generated by "stringer -type=XormEngineGroupPolicy"; DO NOT EDIT.

package dbcommon

import "strconv"

const _XormEngineGroupPolicy_name = "RandomPolicyWeightRandomPolicyRoundRobinPolicyWeightRoundRobinPolicy"

var _XormEngineGroupPolicy_index = [...]uint8{0, 12, 30, 46, 68}

func (i XormEngineGroupPolicy) String() string {
	if i < 0 || i >= XormEngineGroupPolicy(len(_XormEngineGroupPolicy_index)-1) {
		return "XormEngineGroupPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _XormEngineGroupPolicy_name[_XormEngineGroupPolicy_index[i]:_XormEngineGroupPolicy_index[i+1]]
}
